### ISSUE TITLE
As a Moim Community Service, I want to Update a List of Community Members.

### ISSUE THREAD

**Issue by manh-vv** [canfoundation/governance-design#33]
https://canfoundation.atlassian.net/browse/CAN-10

* [ ] new code for updating the member list

@quocle108 @danielAlvess 

@thienlinh cif-js may need to be updated along

**Comment by danielAlvess** [comment]
This feature is under reviewing process in PR https://github.com/canfoundation/governance-design/pull/28

**Comment by quocle108** [comment]
https://github.com/canfoundation/governance-design/pull/28
